### ISSUE TITLE
Issue when converting NewsQA to SQuAD

### ISSUE THREAD

**Issue by pminervini** [alontalmor/MultiQA#10]
Here you go - how can I fix this?

```bash
$ PYTHONPATH=. python3 build_dataset.py --dataset_name NewsQA --split test --output_file newsqa_test.jsonl.gz --n_processes 1
100%|██████████████████████████████████| 12744/12744 [00:00<00:00, 71143.26it/s]
2019-09-18 18:23:23,261 - INFO - datasets.NewsQA.newsqa - producing final context file
100%|████████████████████████████████████████| 637/637 [00:04<00:00, 156.49it/s]
------- dataset header --------
{
    "header": {
        "dataset_name": "NewsQA",
        "split": "test",
        "dataset_url": "https://datasets.maluuba.com/NewsQA",
        "license": "https://datasets.maluuba.com/terms-and-conditions",
        "data_source": "NewsWire",
        "context_answer_detection_source": "NewsQA",
        "tokenization_source": "MultiQA",
        "full_schema": {},
        "text_type": "abstract",
        "number_of_qas": 5412,
        "number_of_contexts": 637,
        "file_num": 1,
        "next_file_exists": false,
        "readme": "",
        "multiqa_version": "0.1.0"
    }
}
$ PYTHONPATH=. python3 ./convert_multiqa_to_squad_format.py --dataset newsqa_test.jsonl.gz --output_file NewsQA_test.squad.jsonl
Traceback (most recent call last):
  File "./convert_multiqa_to_squad_format.py", line 125, in <module>
    main()
  File "./convert_multiqa_to_squad_format.py", line 118, in main
    squad_data = multiqa_to_squad(args.datasets.split(','))
  File "./convert_multiqa_to_squad_format.py", line 77, in multiqa_to_squad
    datasets[ind]['header'] = json.loads(datasets[ind]['file_handle'].readline())['header']
  File "/home/user/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/user/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

**Comment by pminervini** [comment]
Found the issue:

```$ git diff build_dataset.py
diff --git a/build_dataset.py b/build_dataset.py
index cee9428..f865ce7 100644
--- a/build_dataset.py
+++ b/build_dataset.py
@@ -91,7 +91,8 @@ def main():
 
             with open(output_file.replace('.gz',''), "w") as f:
                 # first JSON line is header
-                f.write(json.dumps({'header': header}, indent=4) + '\n')
+                ### f.write(json.dumps({'header': header}, indent=4) + '\n')
+                f.write(json.dumps({'header': header}) + '\n')
                 for instance in contexts:
                     if args.save_in_sample_format:
                         s = json.dumps(instance, indent=4)
```
