### ISSUE TITLE
Error when training with ComQA

### ISSUE THREAD

**Issue by danyaljj** [alontalmor/MultiQA#21]
Looks like it does find the right training data: 
```
(env37) danielk0014-2:MultiQA danielk$ python multiqa.py train --datasets ComQA
2020-02-06 18:36:55,660 - INFO - root - getting headers of the chosen dataset in order to compute learning rate schedule t_total
Traceback (most recent call last):
  File "multiqa.py", line 170, in <module>
    main()
  File "multiqa.py", line 62, in main
    with open(cached_path(header_url),'r') as f:
  File "/Users/danielk/ideaProjects/MultiQA/env37/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 100, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/Users/danielk/ideaProjects/MultiQA/env37/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 227, in get_from_cache
    .format(url, response.status_code))
OSError: HEAD request failed for url https://multiqa.s3.amazonaws.com/data/headers/ComQA_train.json with status code 404

```

**Comment by alontalmor** [comment]
The missing files have been uploaded, thanks for noticing.

**Comment by danyaljj** [comment]
Thanks
